name: Go Test

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ '1.22', '1.23', '1.24' ]
        
    name: Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install dependencies
      run: go mod tidy

    - name: Test
      run: go test -cover ./...
